c_compiler:                 # [win]
  - clang-cl                # [win]
cxx_compiler:               # [win]
  - clang-cl                # [win]
fortran_compiler:           # [win]
  - flang                   # [win]
fortran_compiler_version:   # [win]
  - "21"                    # [win]
