{% set name = "pyoptsparse" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/pyoptsparse/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8b297503d7e07a0cd7360ca6ab299d52f11cae10e7f5bc7889a2f6dd1f752fb2

build:
  number: 1
  skip: true  # [win]
  skip: true  # [python_impl == 'pypy']


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}

  host:
    - python
    - pip
    - numpy
    - swig
    - ipopt
    - libblas
    - liblapack

  run:
    - python
    - numpy
    - sqlitedict >=1.6
    - scipy >1.2
    - mdolab-baseclasses >=1.3.1

test:
  imports:
    - pyoptsparse

  source_files:
    - tests

  requires:
    - pip
    - testflo
    - parameterized
    - setuptools

  commands:
    - testflo --verbose .
    - pip check

about:
  home: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Package for formulating and solving nonlinear constrained optimization problems.
  description: |
    pyOptSparse is an object-oriented framework for formulating and solving
    nonlinear constrained optimization problems in an efficient, reusable, and
    portable manner. It is a fork of pyOpt that uses sparse matrices throughout
    the code to more efficiently handle large-scale optimization problems.
    Interfaces are provided for a number of optimizers -- for the conda package the optimizers
    ALPSO, CONMIN, IPOPT, NSGA2, PSQP, and SLSQP are supported.


  doc_url: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  dev_url: https://github.com/mdolab/pyoptsparse

extra:
  recipe-maintainers:
    - nwu63
    - marcomangano
    - eirikurj
    - whophil
