{% set name = "pyoptsparse" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/pyoptsparse/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b50f2c083a5c403db0721b3ffc0d70949f6cd2fca09d3b57315f837bda924f13

build:
  number: 0
  skip: true  # [win]
  skip: true  # [python_impl == 'pypy']


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}

  host:
    - python
    - pip
    - numpy
    - swig
    - ipopt
    - libblas
    - liblapack

  run:
    - python
    - numpy
    - sqlitedict >=1.6
    - scipy >1.2
    - mdolab-baseclasses >=1.3.1

test:
  imports:
    - pyoptsparse

  source_files:
    - tests

  requires:
    - pip
    - testflo
    - parameterized
    - setuptools

  commands:
    - testflo --verbose .
    - pip check

about:
  home: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Package for formulating and solving nonlinear constrained optimization problems.
  description: |
    pyOptSparse is an object-oriented framework for formulating and solving
    nonlinear constrained optimization problems in an efficient, reusable, and
    portable manner. It is a fork of pyOpt that uses sparse matrices throughout
    the code to more efficiently handle large-scale optimization problems.
    Interfaces are provided for a number of optimizers -- for the conda package the optimizers
    ALPSO, CONMIN, IPOPT, NSGA2, PSQP, and SLSQP are supported.


  doc_url: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  dev_url: https://github.com/mdolab/pyoptsparse

extra:
  recipe-maintainers:
    - nwu63
    - marcomangano
    - eirikurj
    - whophil
