schema_version: 1

context:
  name: pyoptsparse
  version: "2.16.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mdolab/pyoptsparse/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1590f890892e34ccab9e0685e1c5dd57e23b82d1a780a20b570d8c08cf82ad96
  patches:
    - skip-test-macOS.patch
    - skip-second-NSGA2-test.patch
    - update-CONMIN-tol.patch

build:
  number: 0
  skip:
    - match(python, "<3.11")
  python:
    entry_points:
      - optview = pyoptsparse.postprocessing.OptView:main
      - optview_dash = pyoptsparse.postprocessing.OptView_dash:main

requirements:
  build:
    - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - numpy
    - ninja
    - swig
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}

  host:
    - python
    - python-build
    - pip
    - meson-python
    - ninja
    - numpy

  run:
    - python
    - numpy >=1.25
    - scipy >=1.11
    - sqlitedict >=1.6
    - mdolab-baseclasses >=1.3.1
    - packaging

tests:
  - python:
      imports:
        - pyoptsparse
      pip_check: true
  - files:
      source:
        - tests
    requirements:
      run:
        - pip
        - testflo
        - parameterized
        - setuptools
        - cyipopt
    script:
      - testflo -n 1 --pre_announce --verbose .

about:
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Package for formulating and solving nonlinear constrained optimization problems.
  description: |
    pyOptSparse is an object-oriented framework for formulating and solving
    nonlinear constrained optimization problems in an efficient, reusable, and
    portable manner. It is a fork of pyOpt that uses sparse matrices throughout
    the code to more efficiently handle large-scale optimization problems.
    Interfaces are provided for a number of optimizers -- for the conda package the optimizers
    ALPSO, CONMIN, IPOPT, NSGA2, PSQP, and SLSQP are supported.


  homepage: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  repository: https://github.com/mdolab/pyoptsparse
  documentation: https://mdolab-pyoptsparse.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - ewu63
    - marcomangano
    - eirikurj
    - whophil
